<h1 class="text-center mt-5 mb-5">Simple Chat Test Project</h1>

<form class="d-flex justify-content-center mb-4">
    <div class="form-group mx-sm-3 mb-2">
        <label for="messageText" class="sr-only">Message Text</label>
        <input type="text" class="form-control" id="messageText" placeholder="Let's type something here!">
    </div>
    <button type="submit" class="btn btn-success mb-2">Send</button>
</form>

<div class="border rounded p-3">
    <table class="table">
        <thead>
            <tr>
                <th scope="col" width="250px">created</th>
                <th scope="col">text</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>2020-02-03</td>
                <td>Hello World!</td>
            </tr>
        </tbody>
    </table>
</div>